server:
  port: 8082

spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/bookings
    username: booking
    password: booking
    hikari:
      maximum-pool-size: 10

  jpa:
    hibernate:
      ddl-auto: none
    open-in-view: false
    properties:
      hibernate.format_sql: true

  sql:
    init:
      mode: always

  cloud:
    openfeign:
      client:
        config:
          default:
            connectTimeout: 2000
            readTimeout: 3000
            loggerLevel: BASIC

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    prefer-ip-address: true
    ip-address: 127.0.0.1
    instance-id: ${spring.application.name}:${server.port}
    nonSecurePort: ${server.port}

logging:
  level:
    org.springframework: info
    org.hibernate.SQL: warn
    org.hibernate.orm.jdbc.bind: warn
