server:
  port: 8080

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      server:
        webflux:
          discovery:
            locator:
              enabled: true
              lower-case-service-id: true
          httpclient:
            connect-timeout: 1000      # ms
            response-timeout: 3s
          routes:
            - id: flight-search-route
              uri: lb://flight-search-service
              predicates:
                - Path=/api/flights/**
            - id: booking-route
              uri: lb://booking-service
              predicates:
                - Path=/api/bookings/**
            - id: pricing-route
              uri: lb://pricing-service
              predicates:
                - Path=/api/pricing/**

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${server.port}

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,gateway,env
logging:
  level:
    org.springframework.cloud.gateway: info
