spring:
  application:
    name: booking-service
  cloud:
    config:
      fail-fast: false

  config:
    import: "configserver:http://localhost:8888/"
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8099/realms/travel

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus,metrics,loggers
    health:
      probes:
        enabled: true
    tracing:
      sampling:
        probability: 1.0
  otlp:
    tracing:
      export:
        enabled: false

otel:
  exporter:
    otlp:
      endpoint: http://localhost:4317
