server:
  port: 8761

spring:
  application:
    name: discovery-service
  config:
    import: "configserver:http://localhost:8888/"

management:
  endpoints:
    web:
      exposure:
        include: health,info