server:
  port: 8888

spring:
  application:
    name: config-service
  profiles:
    active: native
  cloud:
    config:
      server:
        native:
          search-locations: "file:/C:/WorkSpace/Alten/Spring-cloud/config-service/config-repo"

management:
  endpoints:
    web:
      exposure:
        include: health,info,env,refresh
  endpoint:
    health:
      show-details: when_authorized
logging:
  level:
    org.springframework.cloud.config.server: info